In [1]:
%pip install matplotlib pandas numpy seaborn wordcloud

Requirement already satisfied: matplotlib in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (3.7.2)
Requirement already satisfied: pandas in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (2.1.0)
Requirement already satisfied: numpy in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (1.25.2)
Requirement already satisfied: seaborn in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (0.13.0)
Requirement already satisfied: wordcloud in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (1.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.1.0)
Requirement already satisfied: cycler>=0.10 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (4.42.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (23.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (10.0.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
raw_df = pd.read_csv('Data\officialbhafc.csv')

In [4]:
raw_df

,post_id,text,post_text,shared_text,original_text,time,timestamp,image,image_lowquality,images,...,reaction_count,with,page_id,sharers,image_id,image_ids,video_ids,videos,was_live,fetched_time
0,917052499787454,This front two… 🤩🔥\n\nHai mặt trước này... 🤩🔥,This front two… 🤩🔥\n\nHai mặt trước này... 🤩🔥,NaN,This front two… 🤩🔥,2023-11-25 23:03:58,1700928238,https://scontent.fhan14-4.fna.fbcdn.net/v/t39....,https://scontent.fhan14-4.fna.fbcdn.net/v/t39....,['https://scontent.fhan14-4.fna.fbcdn.net/v/t3...,...,1498,NaN,95602073138,NaN,NaN,[],[],[],False,2023-11-26 00:05:39.311192
1,917010603124977,"Afternoon, Albion! 😁👋\n\nChào buổi chiều, Albi...","Afternoon, Albion! 😁👋\n\nChào buổi chiều, Albi...",NaN,"Afternoon, Albion! 😁👋",2023-11-25 21:46:40,1700923600,https://scontent.fhan14-3.fna.fbcdn.net/v/t39....,https://scontent.fhan14-3.fna.fbcdn.net/v/t39....,['https://scontent.fhan14-3.fna.fbcdn.net/v/t3...,...,1725,NaN,95602073138,NaN,NaN,[],[],[],False,2023-11-26 00:06:01.359878
2,916986813127356,TEAM NEWS! 🚨Here's our #NFOBHA starting XI. 👀📝...,TEAM NEWS! 🚨Here's our #NFOBHA starting XI. 👀📝...,NaN,TEAM NEWS! 🚨Here's our #NFOBHA starting XI. 👀📝,2023-11-25 21:00:25,1700920825,https://scontent.fhan14-3.fna.fbcdn.net/v/t39....,https://scontent.fhan14-3.fna.fbcdn.net/v/t39....,['https://scontent.fhan14-3.fna.fbcdn.net/v/t3...,...,1624,"[{'name': 'Snickers UK', 'link': 'https://face...",95602073138,NaN,9.169848e+14,['916984803127557'],NaN,NaN,False,2023-11-26 00:06:51.123493
3,916925506466820,Facundo’s first Albion goal came against Fores...,Facundo’s first Albion goal came against Fores...,NaN,Facundo’s first Albion goal came against Fores...,2023-11-25 18:34:24,1700912064,NaN,https://scontent.fhan14-3.fna.fbcdn.net/v/t51....,[],...,440,NaN,95602073138,NaN,NaN,[],NaN,NaN,False,2023-11-26 00:07:21.222600
4,916913676468003,An UNFORGETTABLE last minute win at Forest bac...,An UNFORGETTABLE last minute win at Forest bac...,NaN,An UNFORGETTABLE last minute win at Forest bac...,2023-11-25 18:03:08,1700910188,NaN,https://scontent.fhan14-4.fna.fbcdn.net/v/t15....,[],...,355,NaN,95602073138,NaN,NaN,[],NaN,NaN,False,2023-11-26 00:07:31.253557
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,904378794388158,Steeley is here to stay! 💙🤍\n\nSteeley ở đây đ...,Steeley is here to stay! 💙🤍\n\nSteeley ở đây đ...,NaN,Steeley is here to stay! 💙🤍,2023-11-02 18:52:05,1698925925,NaN,https://scontent.fhan14-4.fna.fbcdn.net/v/t51....,[],...,1046,NaN,95602073138,NaN,NaN,[],NaN,NaN,False,2023-11-26 02:09:24.928664
96,904319421060762,Jason Steele has further committed his future ...,Jason Steele has further committed his future ...,NaN,NaN,2023-11-02 16:00:16,1698915616,https://scontent.fhan14-3.fna.fbcdn.net/v/t39....,https://scontent.fhan14-3.fna.fbcdn.net/v/t39....,['https://scontent.fhan14-3.fna.fbcdn.net/v/t3...,...,4212,NaN,95602073138,NaN,NaN,[],[],[],False,2023-11-26 02:09:38.464149
97,904093027750068,Our first British Airways Player of the Match!...,Our first British Airways Player of the Match!...,NaN,Our first British Airways Player of the Match!...,2023-11-02 03:57:23,1698872243,https://m.facebook.com/photo/view_full_size/?f...,https://scontent.fhan14-4.fna.fbcdn.net/v/t39....,['https://m.facebook.com/photo/view_full_size/...,...,4799,NaN,95602073138,NaN,9.040925e+14,['904092457750125'],NaN,NaN,False,2023-11-26 02:10:07.444783
98,904065187752852,Dunky is an @easportsfc Centurion. 🤩🐐\n\nDunky...,Dunky is an @easportsfc Centurion. 🤩🐐\n\nDunky...,NaN,Dunky is an @easportsfc Centurion. 🤩🐐,2023-11-02 02:23:15,1698866595,https://scontent.fhan14-2.fna.fbcdn.net/v/t39....,https://scontent.fhan14-2.fna.fbcdn.net/v/t39....,['https://scontent.fhan14-2.fna.fbcdn.net/v/t3...,...,1992,NaN,95602073138,NaN,NaN,[],[],[],False,2023-11-26 02:10:29.974844
99,903904937768877,The best of Pascal’s 200 #PL appearances! 🔥\n\...,The best of Pascal’s 200 #PL appearances! 🔥\n\...,NaN,The best of Pascal’s 200 #PL appearances! 🔥,2023-11-01 20:15:07,1698844507,NaN,https://scontent.fhan14-4.fna.fbcdn.net/v/t51....,[],...,753,NaN,95602073138,NaN,NaN,[],NaN,NaN,False,2023-11-26 02:10:43.619642

Tách riêng để phân loại các reactions

In [5]:
raw_df['reactions'] = raw_df['reactions'].apply(lambda x : dict(eval(x)) )
df_detailReactions = raw_df['reactions'].apply(pd.Series )

C:\Users\Admin\AppData\Local\Temp\ipykernel_23688\3969651814.py:2: FutureWarning: Returning a DataFrame from Series.apply when the supplied function returns a Series is deprecated and will be removed in a future version.
  df_detailReactions = raw_df['reactions'].apply(pd.Series )

In [6]:
raw_df = pd.concat([raw_df, df_detailReactions], axis=1).drop('reactions',axis=1)
raw_df[['post_id','thích','yêu thích','haha','wow','buồn','phẫn nộ','thương thương',
                                 'shares','comments','reaction_count']]

,post_id,thích,yêu thích,haha,wow,buồn,phẫn nộ,thương thương,shares,comments,reaction_count
0,917052499787454,1236.0,247.0,NaN,1.0,NaN,NaN,14.0,12,27,1498
1,917010603124977,1478.0,230.0,2.0,NaN,NaN,NaN,15.0,8,55,1725
2,916986813127356,1371.0,235.0,1.0,1.0,3.0,NaN,13.0,34,103,1624
3,916925506466820,374.0,61.0,2.0,NaN,NaN,NaN,3.0,7,9,440
4,916913676468003,317.0,36.0,NaN,NaN,NaN,NaN,2.0,9,15,355
...,...,...,...,...,...,...,...,...,...,...,...
95,904378794388158,934.0,106.0,NaN,NaN,1.0,NaN,5.0,28,14,1046
96,904319421060762,3712.0,471.0,3.0,5.0,1.0,3.0,17.0,52,125,4212
97,904093027750068,4158.0,604.0,NaN,1.0,NaN,2.0,34.0,20,50,4799
98,904065187752852,1709.0,261.0,NaN,1.0,NaN,2.0,19.0,10,14,1992
99,903904937768877,661.0,85.0,NaN,2.0,NaN,NaN,5.0,22,12,753

Loại bỏ những hàng mà không có giá trị của những trường chính

In [7]:
raw_df=raw_df.dropna(subset=['text','post_text','reaction_count','video'],how='all')

In [8]:
raw_df=raw_df.dropna(subset=['reaction_count'],how='all')

Xóa đi các cột và các hàng không chứa giá trị

In [9]:
raw_df=raw_df.dropna(how='all')

In [10]:
raw_df=raw_df.dropna(axis=1,how='all')

Kiểm tra và loại bỏ những dòng dữ liệu trùng lặp trong dataframe

In [11]:
raw_df=raw_df.drop_duplicates()

In [12]:
raw_df.fillna(0,inplace=True)

In [13]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 45 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   post_id                        100 non-null    int64
 1   text                           100 non-null    object
 2   post_text                      100 non-null    object
 3   shared_text                    100 non-null    object
 4   original_text                  100 non-null    object
 5   time                           100 non-null    object
 6   timestamp                      100 non-null    int64
 7   image                          100 non-null    object
 8   image_lowquality               100 non-null    object
 9   images                         100 non-null    object
 10  images_description             100 non-null    object
 11  images_lowquality              100 non-null    object
 12  images_lowquality_description  100 non-null    object
 13  video                          100 non-null    object
 14  video_id                       100 non-null    float64
 15  video_thumbnail                100 non-null    object
 16  comments                       100 non-null    int64
 17  shares                         100 non-null    int64
 18  post_url                       100 non-null    object
 19  link                           100 non-null    object
 20  links                          100 non-null    object
 21  user_id                        100 non-null    int64
 22  username                       100 non-null    object
 23  user_url                       100 non-null    object
 24  is_live                        100 non-null    bool
 25  available                      100 non-null    bool
 26  comments_full                  100 non-null    object
 27  reactors                       100 non-null    object
 28  w3_fb_url                      100 non-null    object
 29  reaction_count                 100 non-null    int64
 30  with                           100 non-null    object
 31  page_id                        100 non-null    int64
 32  image_id                       100 non-null    float64
 33  image_ids                      100 non-null    object
 34  video_ids                      100 non-null    object
 35  videos                         100 non-null    object
 36  was_live                       100 non-null    bool
 37  fetched_time                   100 non-null    object
 38  thích                          100 non-null    float64
 39  yêu thích                      100 non-null    float64
 40  wow                            100 non-null    float64
 41  thương thương                  100 non-null    float64
 42  haha                           100 non-null    float64
 43  buồn                           100 non-null    float64
 44  phẫn nộ                        100 non-null    float64
dtypes: bool(3), float64(9), int64(7), object(26)
memory usage: 33.2+ KB

In [14]:
raw_df

,post_id,text,post_text,shared_text,original_text,time,timestamp,image,image_lowquality,images,...,videos,was_live,fetched_time,thích,yêu thích,wow,thương thương,haha,buồn,phẫn nộ
0,917052499787454,This front two… 🤩🔥\n\nHai mặt trước này... 🤩🔥,This front two… 🤩🔥\n\nHai mặt trước này... 🤩🔥,0,This front two… 🤩🔥,2023-11-25 23:03:58,1700928238,https://scontent.fhan14-4.fna.fbcdn.net/v/t39....,https://scontent.fhan14-4.fna.fbcdn.net/v/t39....,['https://scontent.fhan14-4.fna.fbcdn.net/v/t3...,...,[],False,2023-11-26 00:05:39.311192,1236.0,247.0,1.0,14.0,0.0,0.0,0.0
1,917010603124977,"Afternoon, Albion! 😁👋\n\nChào buổi chiều, Albi...","Afternoon, Albion! 😁👋\n\nChào buổi chiều, Albi...",0,"Afternoon, Albion! 😁👋",2023-11-25 21:46:40,1700923600,https://scontent.fhan14-3.fna.fbcdn.net/v/t39....,https://scontent.fhan14-3.fna.fbcdn.net/v/t39....,['https://scontent.fhan14-3.fna.fbcdn.net/v/t3...,...,[],False,2023-11-26 00:06:01.359878,1478.0,230.0,0.0,15.0,2.0,0.0,0.0
2,916986813127356,TEAM NEWS! 🚨Here's our #NFOBHA starting XI. 👀📝...,TEAM NEWS! 🚨Here's our #NFOBHA starting XI. 👀📝...,0,TEAM NEWS! 🚨Here's our #NFOBHA starting XI. 👀📝,2023-11-25 21:00:25,1700920825,https://scontent.fhan14-3.fna.fbcdn.net/v/t39....,https://scontent.fhan14-3.fna.fbcdn.net/v/t39....,['https://scontent.fhan14-3.fna.fbcdn.net/v/t3...,...,0,False,2023-11-26 00:06:51.123493,1371.0,235.0,1.0,13.0,1.0,3.0,0.0
3,916925506466820,Facundo’s first Albion goal came against Fores...,Facundo’s first Albion goal came against Fores...,0,Facundo’s first Albion goal came against Fores...,2023-11-25 18:34:24,1700912064,0,https://scontent.fhan14-3.fna.fbcdn.net/v/t51....,[],...,0,False,2023-11-26 00:07:21.222600,374.0,61.0,0.0,3.0,2.0,0.0,0.0
4,916913676468003,An UNFORGETTABLE last minute win at Forest bac...,An UNFORGETTABLE last minute win at Forest bac...,0,An UNFORGETTABLE last minute win at Forest bac...,2023-11-25 18:03:08,1700910188,0,https://scontent.fhan14-4.fna.fbcdn.net/v/t15....,[],...,0,False,2023-11-26 00:07:31.253557,317.0,36.0,0.0,2.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,904378794388158,Steeley is here to stay! 💙🤍\n\nSteeley ở đây đ...,Steeley is here to stay! 💙🤍\n\nSteeley ở đây đ...,0,Steeley is here to stay! 💙🤍,2023-11-02 18:52:05,1698925925,0,https://scontent.fhan14-4.fna.fbcdn.net/v/t51....,[],...,0,False,2023-11-26 02:09:24.928664,934.0,106.0,0.0,5.0,0.0,1.0,0.0
96,904319421060762,Jason Steele has further committed his future ...,Jason Steele has further committed his future ...,0,0,2023-11-02 16:00:16,1698915616,https://scontent.fhan14-3.fna.fbcdn.net/v/t39....,https://scontent.fhan14-3.fna.fbcdn.net/v/t39....,['https://scontent.fhan14-3.fna.fbcdn.net/v/t3...,...,[],False,2023-11-26 02:09:38.464149,3712.0,471.0,5.0,17.0,3.0,1.0,3.0
97,904093027750068,Our first British Airways Player of the Match!...,Our first British Airways Player of the Match!...,0,Our first British Airways Player of the Match!...,2023-11-02 03:57:23,1698872243,https://m.facebook.com/photo/view_full_size/?f...,https://scontent.fhan14-4.fna.fbcdn.net/v/t39....,['https://m.facebook.com/photo/view_full_size/...,...,0,False,2023-11-26 02:10:07.444783,4158.0,604.0,1.0,34.0,0.0,0.0,2.0
98,904065187752852,Dunky is an @easportsfc Centurion. 🤩🐐\n\nDunky...,Dunky is an @easportsfc Centurion. 🤩🐐\n\nDunky...,0,Dunky is an @easportsfc Centurion. 🤩🐐,2023-11-02 02:23:15,1698866595,https://scontent.fhan14-2.fna.fbcdn.net/v/t39....,https://scontent.fhan14-2.fna.fbcdn.net/v/t39....,['https://scontent.fhan14-2.fna.fbcdn.net/v/t3...,...,[],False,2023-11-26 02:10:29.974844,1709.0,261.0,1.0,19.0,0.0,0.0,2.0
99,903904937768877,The best of Pascal’s 200 #PL appearances! 🔥\n\...,The best of Pascal’s 200 #PL appearances! 🔥\n\...,0,The best of Pascal’s 200 #PL appearances! 🔥,2023-11-01 20:15:07,1698844507,0,https://scontent.fhan14-4.fna.fbcdn.net/v/t51....,[],...,0,False,2023-11-26 02:10:43.619642,661.0,85.0,2.0,5.0,0.0,0.0,0.0

Loại bỏ emoji, các ký tự đặc biệt và url

In [15]:
import re

def clean_text(text):

    if isinstance(text,str):
        # loại bỏ các emoji
        text = re.sub(r'[\U00010000-\U0010ffff]','', text)

        # loại bỏ các ký tự đặc biệt 
        text = re.sub(r'[^a-zA-Z0-9\s]', '', text)

        # loại bỏ các đường dẫn
        text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

        return text
raw_df['post_text']=raw_df['post_text'].apply(clean_text)

Chuyển kiểu dữ liệu từ fetched time sang datetime và tách cột datetime thành có trường nhỏ hơn

In [16]:
# Chuyển kiểu dữ liệu của fetched_time sang datetime64
raw_df['time'] = pd.to_datetime(raw_df['time'])

raw_df['hour'] = raw_df['time'].dt.hour
raw_df['day'] = raw_df['time'].dt.day
raw_df['month'] = raw_df['time'].dt.month
raw_df['year'] = raw_df['time'].dt.year
raw_df[['hour', 'day', 'month', 'year']]

    hour  day  month  year
0     23   25     11  2023
1     21   25     11  2023
2     21   25     11  2023
3     18   25     11  2023
4     18   25     11  2023
..   ...  ...    ...   ...
95    18    2     11  2023
96    16    2     11  2023
97     3    2     11  2023
98     2    2     11  2023
99    20    1     11  2023

[100 rows x 4 columns]

In [17]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 49 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   post_id                        100 non-null    int64
 1   text                           100 non-null    object
 2   post_text                      97 non-null     object
 3   shared_text                    100 non-null    object
 4   original_text                  100 non-null    object
 5   time                           100 non-null    datetime64[ns]
 6   timestamp                      100 non-null    int64
 7   image                          100 non-null    object
 8   image_lowquality               100 non-null    object
 9   images                         100 non-null    object
 10  images_description             100 non-null    object
 11  images_lowquality              100 non-null    object
 12  images_lowquality_description  100 non-null    object
 13  video                          100 non-null    object
 14  video_id                       100 non-null    float64
 15  video_thumbnail                100 non-null    object
 16  comments                       100 non-null    int64
 17  shares                         100 non-null    int64
 18  post_url                       100 non-null    object
 19  link                           100 non-null    object
 20  links                          100 non-null    object
 21  user_id                        100 non-null    int64
 22  username                       100 non-null    object
 23  user_url                       100 non-null    object
 24  is_live                        100 non-null    bool
 25  available                      100 non-null    bool
 26  comments_full                  100 non-null    object
 27  reactors                       100 non-null    object
 28  w3_fb_url                      100 non-null    object
 29  reaction_count                 100 non-null    int64
 30  with                           100 non-null    object
 31  page_id                        100 non-null    int64
 32  image_id                       100 non-null    float64
 33  image_ids                      100 non-null    object
 34  video_ids                      100 non-null    object
 35  videos                         100 non-null    object
 36  was_live                       100 non-null    bool
 37  fetched_time                   100 non-null    object
 38  thích                          100 non-null    float64
 39  yêu thích                      100 non-null    float64
 40  wow                            100 non-null    float64
 41  thương thương                  100 non-null    float64
 42  haha                           100 non-null    float64
 43  buồn                           100 non-null    float64
 44  phẫn nộ                        100 non-null    float64
 45  hour                           100 non-null    int32
 46  day                            100 non-null    int32
 47  month                          100 non-null    int32
 48  year                           100 non-null    int32
dtypes: bool(3), datetime64[ns](1), float64(9), int32(4), int64(7), object(25)
memory usage: 34.8+ KB

In [18]:
FANPAGE_LINK ="officialbhafc"
FOLDER_PATH = "Data/"
# To csv
path=FOLDER_PATH + FANPAGE_LINK +"_after" ".csv"
raw_df.to_csv(path, index=False)
print(path)

Data/officialbhafc_after.csv